apiVersion: apps/v1
kind: Deployment
metadata:
  name: ju-ajae-deployment # deployment 이름
  labels:
    app: ajae-bot
spec:
  replicas: {{.Values.replicaCount}} # pod 1개
  selector:
    matchLabels:
      app: ajae-bot
  template:
    metadata:
      labels:
        app: ajae-bot
    spec: # Pod spec
      containers:
      - name: ajae-container
        image: {{ .Values.image.repository}}:{{.Values.image.tag }} # version 명시 하지 않을 경우 deault 로 `latest` 로 인식한다.
        env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: juyoung-slack # k8s secret 명
              key: token
              optional: false # 반드시 있어야 실행
        imagePullPolicy: {{.Values.image.pullPolicy}}
      imagePullSecrets: # image pull 받기 위한 github token file (secret)
      - name: juyoung-github # github credentials 로 생성한 secret

