apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: juyoung-slack
  namespace: default
spec:
  encryptedData:
    token: AgBc1bBcFiCjjWCvWHc6pZrNCVNxI6iLyG+MfG3AzLU3GVYTqpjFN5qkJJVIPRiH3qxRx9ObD7v4TAc+xrmlxPvme5ydNxOm4KIzbn5jcL9ox/j9V62xPOU5tQcMLg7VLYubuNIdGRasRUQNzMi8KMQ7I+huu75vVojnGpDsw9ZzZ6o4WJyC1Z490pt+9KmUT+ZS7ZatrpxTfq9EQWthxTAICbc1MyK494duGNxcNXAAqHct1FZP5R4XuAIjRSZMlC9V5lmHvseg/K7YpKapc6EE4tv3lLBdjDuE2gAN01KTEac7XdUmdOmV5KSttlvmutqJKVPXf8CmAiInn/vj6K88gtIwuoVDTSSYnO1eG5WsUepmodBZy2ZEAa60Y5SJVrbNWdN0gPM+vVsB8TdGvSgFF0UUf5ozyXYzHFf9a+qQhoMy9mIkaMdTJhgwxxXN8irz7NthKcs1YnUJVXdYG71wdupAWQcNDVNyz2kl/DORg+YhZRoCtpJPPTQ57iMEu4ha7XT5JqnhV/geJ5t3QwpIoO5sDpcfAZ6qMtkoOauIebCbHk+HKYDHzvUtFHbaBPzEe75eg905H/fNGz9J6BPwCsOKKIdoKag/b8qd5c8Fp2RhC9wDVlvWVA182FyC13SvvvHv+GURzH6Tr+6zmOIC1smZF5HATUZ1Qv3C2YnBVgC662QeF28sueHokQfFWfNSEgbPh1nt7B2xmXTdfZign65rGRZW/+34V8/q+Ht5bXMZlVGNkIQMpuWmK9Z6l+kczyHX3EqiE5k=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: juyoung-slack
      namespace: default
    type: Opaque